apiVersion: v1
kind: ReplicationController
metadata:
  name: weather102
  labels:
    name: weather102
spec:
  replicas: 1
  selector:
    name: weather102
    version: v0
  template:
    metadata:
      labels:
        name: weather102
        version: v0
    spec:
      containers:
      - name: weather102
        image: gcr.io/chat-app-proto01/weather102:latest
        # env:
        #   - name: ENV
        #     value: production
        # ports:
        # - containerPort: 9000
        #   hostPort: 9000
      # nodeSelector:
      #   kubernetes.io/hostname: gke-beeemock-cluster-899aa15e-node-7svo
